### ISSUE TITLE
How can I change the fonts?

### ISSUE THREAD

**Issue by hzlzh** [hzlzh/Dot-B#2]

**Comment by hzlzh** [comment]
Include font file into `wp-header.php` by adding code like this:

``` html
<link rel='stylesheet' id='googlefonts-css'  href='http://fonts.googleapis.com/css?family=Electrolize:400&subset=latin' type='text/css' media='all' />
```

Then change code `/Dot-B/style.css` **Line 15**:
https://github.com/hzlzh/Dot-B/blob/master/style.css

``` css
body{font:13px/18px "Electrolize",Tahoma,Arial,Helvetica,sans-serif; color:#555; line-height:1}
```
