### ISSUE TITLE
How can I get rid of the search-entry?

### ISSUE THREAD

**Issue by hzlzh** [hzlzh/Dot-B#3]
![Screen Shot 2013-02-09 at 1 23 03 AM](https://f.cloud.github.com/assets/1049575/140175/500c3734-7214-11e2-800c-116d26191650.png)

**Comment by hzlzh** [comment]
You can remove the search area by adding those CSS style code below into `/dot-b/style.css`

``` css
#header_search_area{display:none;}
```
