### ISSUE TITLE
How to change the RSS icon image into your own image?

### ISSUE THREAD

**Issue by hzlzh** [hzlzh/Dot-B#8]
### One way:

You can cover the `old image` named `all.png` by tools like `Photoshop`
Location: `http://xxxx.xxxx.com/wp-content/themes/dot-b/images/all.png`
### Another way:

Add a new CSS style to the theme file `style.css` to the bottom.
Please save that image into your FTP and replace the image URL.

``` css
#header #rss {
    background: url("https://dl.dropboxusercontent.com/u/13642414/temp/facebook.png") repeat scroll 0 0 transparent;
}
#header #rss:hover {
    background: url("https://dl.dropboxusercontent.com/u/13642414/temp/facebook.png") repeat scroll 0 0 transparent;
}
```

then you can see the new image there like the screenshot belwo:
![after](https://f.cloud.github.com/assets/1049575/392118/279ad8ea-a776-11e2-8f0c-8b1ae61304f9.png)

**Comment by hzlzh** [comment]
``` css
#header #rss {
    display:none;
}
```

to remove that  RSS icon.
